# create kubernetes secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:  # Create a secret via terminal  ->  echo -n 'username' | base64    this will give us this dXNlcm5hbWU=
  mongo-username: dXNlcm5hbWU=
  mongo-password: cGFzc3dvcmQ=